permalink: pretty
name: Daniel Tull

opensourcetitle: Open Source Code
opensourcenames: ['Resurrection Kit', 'DTNibHook', 'DTGridView', 'DTMusicModel']
opensourceurls: ['http://bitbucket.org/danielctull/dtresurrectionkit', 'http://bitbucket.org/danielctull/dtnibhook', 'http://bitbucket.org/danielctull/dtgridview/', 'http://bitbucket.org/danielctull/dtmusicmodel/']

servicetitle: Find me on
servicenames: []
serviceurls: []

apptitle: Apps
appnames: []
appurls: []

abouttitle: About
aboutnames: []
abouturls: []