permalink: pretty
name: Daniel Tull

opensourcenames: ['Resurrection Kit', 'DTNibHook', 'DTGridView' , 'DTMusicModel']
opensourceurls: ['http://bitbucket.org/danielctull/dtresurrectionkit', 'http://bitbucket.org/danielctull/dtnibhook', 'http://bitbucket.org/danielctull/dtgridview/', 'http://bitbucket.org/danielctull/dtmusicmodel/']
