permalink: pretty
name: Daniel Tull

opensourcetitle: Open Source Code
opensourcenames: ['Resurrection Kit', 'DTNibHook', 'DTGridView', 'DTMusicModel']
opensourceurls: ['http://bitbucket.org/danielctull/dtresurrectionkit', 'http://bitbucket.org/danielctull/dtnibhook', 'http://bitbucket.org/danielctull/dtgridview/', 'http://bitbucket.org/danielctull/dtmusicmodel/']

servicetitle: Find me on
servicenames: ['Twitter']
serviceurls: ['http://www.twitter.com/danielctull']

apptitle: Apps
appnames: ['Weather Maps', 'Sky+']
appurls: ['http://www.weathermapsapp.com/', 'http://itunes.apple.com/gb/app/sky/id301250225?mt=8']

abouttitle: About
aboutnames: ['Contact']
abouturls: ['/contact/']